### PR TITLE
Bump/0.26

### PR DESCRIPTION
**Pull request by eliegaboriau**
This PR bumps the decidim version from 0.24 to 0.26.
It : 
 - updates the CI
 - bumps decidim version, and related gems
 - bumps ruby version
 - updates overloads.md
 - migrates to webpack (add packages, manage fonts, manages css)
 - updates files from decidim that are still required
 - remove files from decidim that are no longer required
 - remove locales no longer needed
 - add migrations
 - updates spec

### CODE REVIEW

**Review by paulinebessoles — APPROVED** [review]
Thank you for this PR @eliegaboriau ! 

Everything works perfectly in local, but I just wonder if we shouldn't also delete the 
`app/controllers/decidim/proposals/proposals_controller.rb` file.

**Comment by eliegaboriau** [comment]
Hello @paulinebessoles , the override is not the same as the file on decidim.
I think we should keep it unless we don't need the feature anymore

**Comment by eliegaboriau** [comment]
Hello @paulinebessoles , the override is not the same as the file on decidim.
I think we should keep it unless we don't need the feature anymore

**Comment by paulinebessoles** [comment]
I think we made the fix differently than Decidim at this moment, could you check in the different files if the outcome is supposed to be the same?

**Comment by eliegaboriau** [comment]
It looks like it's not fixed on Decidim.

**Pull request merged**
